---
title: "Sanity checks on accuracy calculation and iteration stability"
author: "Paul Mätzig"
date: "4/4/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.height=8,fig.width=8)
library(dplyr)
library(ggplot2)
library(plotly)
library(plot3D)         ## for 3D scatterplots
library(scatterplot3d)  ## for 3D scatterplots
library(ggplot2)
library(ggdendro)
library(factoextra)
```

```{r loaddata, echo=FALSE}
caplan_data <- read.table('../data/CaplanEtAl_2015_data.txt', header=TRUE)
model_data_SR <- read.csv('../data/response_accuracies_GG_SR_2017016_1736.csv', header=TRUE)
model_data_guess_SR <- read.csv('../data/response_accuracies_guess_GG_SR_2017016_1736.csv')
model_data_OR <- read.csv('../data/response_accuracies_GG_OR_2017018_1827.csv', header=TRUE)
model_data_guess_OR <- read.csv('../data/response_accuracies_guess_GG_OR_2017018_1827.csv')
caplan_data$sent <- as.character(caplan_data$sent)

caplan_data_SR <- filter(caplan_data, sent=='SS')
caplan_data_OR <- filter(caplan_data, sent=='SO')
```

```{r runallchunks,echo=FALSE}
# This is a utility to run all chunks in a given .Rmd file through
# a temporary R file to load everything into the global environment
# of RStudio.

runAllChunks <- function(rmd, envir=globalenv()) {
  tempR <- tempfile(tmpdir = ".", fileext = ".R")
  on.exit(unlink(tempR))
  knitr::purl(rmd, output=tempR)
  sys.source(tempR, envir=envir)
}
```

```{r preprocessdata,echo=FALSE}
# data are not balanced, see:
#xtabs(~subj+item, caplan_data_SR)
#xtabs(~subj+item, caplan_data_OR)

caplan_data_SR_acc <- summarise(group_by(caplan_data_SR, subj,item), sum(acc) / n())
#head(caplan_data_SR_acc)
#summary(caplan_data_SR_acc)
#xtabs(~subj+item, caplan_data_SR_acc)
colnames(caplan_data_SR_acc) <- c('subj', 'item', 'acc')
caplan_data_SR_acc <- summarise(group_by(caplan_data_SR_acc, subj), sum(acc) / n())
colnames(caplan_data_SR_acc)<-c('subj', 'acc')
#summary(caplan_data_SR_acc)

caplan_data_OR_acc <- summarise(group_by(caplan_data_OR, subj,item), sum(acc) / n())
colnames(caplan_data_OR_acc) <- c('subj', 'item', 'acc')
#head(caplan_data_OR_acc)
#summary(caplan_data_OR_acc)
#xtabs(~subj+item, caplan_data_OR_acc)
caplan_data_OR_acc <- summarise(group_by(caplan_data_OR_acc, subj), sum(acc) / n())
colnames(caplan_data_OR_acc)<-c('subj', 'acc')
#summary(caplan_data_OR_acc)

slots_SR <- matrix(rep(NA, dim(model_data_SR)[1]*dim(caplan_data_SR_acc)[1]), ncol=dim(caplan_data_SR_acc)[1])
slots_OR <- matrix(rep(NA, dim(model_data_OR)[1]*dim(caplan_data_OR_acc)[1]), ncol=dim(caplan_data_OR_acc)[1])

for (i in 1:length(caplan_data_SR_acc$subj)) {
  tmp_acc <- caplan_data_SR_acc$acc[i]
  slots_SR[,i] <- abs(model_data_SR$acc - tmp_acc)
}

for (i in 1:length(caplan_data_OR_acc$subj)) {
  tmp_acc <- caplan_data_OR_acc$acc[i]
  slots_OR[,i] <- abs(model_data_OR$acc - tmp_acc)
}

colnames(slots_SR) <- paste("s", caplan_data_SR_acc$subj, sep = "")
colnames(slots_OR) <- paste("s", caplan_data_OR_acc$subj, sep = "")

model_data_SR <- cbind(model_data_SR, slots_SR)
model_data_OR <- cbind(model_data_OR, slots_OR)

get_min_params <- function(data, subject) {
  ref <- which(data[c(subject)]==min(data[c(subject)]))
  params <- data[ref, c("GA", "DAT", "ANS", "acc")]
  return(params)
}

subjects_SR <- colnames(model_data_SR)[9:dim(model_data_SR)[2]]
subjects_OR <- colnames(model_data_OR)[9:dim(model_data_OR)[2]]

results_SR <- data.frame()
for (i in 1:length(subjects_SR)) {
  tmp <- get_min_params(model_data_SR, subjects_SR[i])
  tmp$subj <- rep(subjects_SR[i], dim(tmp)[1])
  results_SR <- rbind(results_SR, tmp, make.row.names=FALSE)
}

#subjects<-unique(results_SR$subj)
#for(i in 1:length(subjects)){
#print(dim(subset(results_SR,subj==subjects[i]))[1])
#}
  
results_OR <- data.frame()
for (i in 1:length(subjects_OR)) {
  tmp <- get_min_params(model_data_OR, subjects_OR[i])
  tmp$subj <- rep(subjects_OR[i], dim(tmp)[1])
  results_OR <- rbind(results_OR, tmp, make.row.names=FALSE)
}

## splitting data by SR/OR condition and by control/IWA group
results_SR_controls <- results_SR[1:(min(which(results_SR$subj=="s54001"))-1), ]
results_SR_iwa <- results_SR[min(which(results_SR$subj=="s54001")):dim(results_SR)[1], ]
results_OR_controls <- results_OR[1:(min(which(results_OR$subj=="s54001"))-1), ]
results_OR_iwa <- results_OR[min(which(results_OR$subj=="s54001")):dim(results_OR)[1], ]

results_OR_controls$type <- "control"
results_OR_iwa$type <- "iwa"
results_OR <- rbind(results_OR_controls, results_OR_iwa)

results_SR_controls$type <- "control"
results_SR_iwa$type <- "iwa"
results_SR <- rbind(results_SR_controls, results_SR_iwa)

results_SR$RCType <- "SR"
results_OR$RCType <- "OR"

results_all <- rbind(results_SR, results_OR)
```


```{r preprocessdata_guess, echo=FALSE}
slots_guess_SR <- matrix(rep(NA, dim(model_data_guess_SR)[1]*dim(caplan_data_SR_acc)[1]), ncol=dim(caplan_data_SR_acc)[1])
slots_guess_OR <- matrix(rep(NA, dim(model_data_guess_OR)[1]*dim(caplan_data_OR_acc)[1]), ncol=dim(caplan_data_OR_acc)[1])

for (i in 1:length(caplan_data_SR_acc$subj)) {
  tmp_acc <- caplan_data_SR_acc$acc[i]
  slots_guess_SR[,i] <- abs(model_data_guess_SR$acc - tmp_acc)
}

for (i in 1:length(caplan_data_OR_acc$subj)) {
  tmp_acc <- caplan_data_OR_acc$acc[i]
  slots_guess_OR[,i] <- abs(model_data_guess_OR$acc - tmp_acc)
}

colnames(slots_guess_SR) <- paste("s", caplan_data_SR_acc$subj, sep = "")
colnames(slots_guess_OR) <- paste("s", caplan_data_OR_acc$subj, sep = "")

model_data_guess_SR <- cbind(model_data_guess_SR, slots_guess_SR)
model_data_guess_OR <- cbind(model_data_guess_OR, slots_guess_OR)

subjects_guess_SR <- colnames(model_data_guess_SR)[9:dim(model_data_guess_SR)[2]]
subjects_guess_OR <- colnames(model_data_guess_OR)[9:dim(model_data_guess_OR)[2]]

results_guess_SR <- data.frame()
for (i in 1:length(subjects_guess_SR)) {
  tmp <- get_min_params(model_data_guess_SR, subjects_guess_SR[i])
  tmp$subj <- rep(subjects_guess_SR[i], dim(tmp)[1])
  results_guess_SR <- rbind(results_guess_SR, tmp, make.row.names=FALSE)
}

results_guess_OR <- data.frame()
for (i in 1:length(subjects_guess_OR)) {
  tmp <- get_min_params(model_data_guess_OR, subjects_guess_OR[i])
  tmp$subj <- rep(subjects_guess_OR[i], dim(tmp)[1])
  results_guess_OR <- rbind(results_guess_OR, tmp, make.row.names=FALSE)
}

## splitting data by SR/OR condition and by control/IWA group
results_guess_SR_controls <- results_guess_SR[1:(min(which(results_guess_SR$subj=="s54001"))-1), ]
results_guess_SR_iwa <- results_guess_SR[min(which(results_guess_SR$subj=="s54001")):dim(results_guess_SR)[1], ]
results_guess_OR_controls <- results_guess_OR[1:(min(which(results_guess_OR$subj=="s54001"))-1), ]
results_guess_OR_iwa <- results_guess_OR[min(which(results_guess_OR$subj=="s54001")):dim(results_guess_OR)[1], ]

results_guess_OR_controls$type <- "control"
results_guess_OR_iwa$type <- "iwa"
results_guess_OR <- rbind(results_guess_OR_controls, results_guess_OR_iwa)

results_guess_SR_controls$type <- "control"
results_guess_SR_iwa$type <- "iwa"
results_guess_SR <- rbind(results_guess_SR_controls, results_guess_SR_iwa)

results_guess_SR$RCType <- "SR"
results_guess_OR$RCType <- "OR"

results_guess_all <- rbind(results_guess_SR, results_guess_OR)
```
